# Generated by Django 5.2.2 on 2025-06-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='birthday',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
