# Generated by Django 5.2.2 on 2025-06-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0002_alter_birthday_options_alter_birthday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthday',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
